project:
  type: website
  output-dir: _site
  preview:
    port: 7777
    browser: false

website:
  title: "Dr. Vivek Deulkar"
  navbar:
    logo: images/plaksha-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      # - href: blog/index.qmd
      #   text: Blog
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  page-footer:
    center: |
      © 2025 Dr. Vivek Deulkar
    # | Assistant Professor at Plaksha University
    # right: |
    #   Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    code-tools: false
    code-copy: true
    highlight-style: github
